###########
# site.title

title:    'TowerMasters'
subtitle: 'CS 175: Project in AI'
description: Training RL agents to conquer Obstacle Tower
theme: jekyll-theme-minimal


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
